# SwiftLint Configuration for Secure Access Gateway

# Paths to include during linting
included:
  - Sources

# Paths to ignore during linting
excluded:
  - .build
  - .swiftpm
  - Tests
  - Public

# Enabled rules
opt_in_rules:
  - explicit_type_interface
  - fatal_error_message
  - implicitly_unwrapped_optional
  - let_var_whitespace
  - literal_expression_end_indentation
  - modifier_order
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - redundant_nil_coalescing
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 40
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - ip

# Require explicit types for constants and variables at file/type scope
explicit_type_interface:
  excluded:
    - local

# Custom rules
custom_rules:
  security_comment:
    name: "Security Comment"
    regex: "(TODO|FIXME).*security"
    match_kinds:
      - comment
    message: "Security-related TODOs should be tracked in issues"
    severity: warning
